name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: label change test1
      run: | 
        pwd
        ls
        tree
    - name: label change test2
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.